config/routes.rb
Quizlet::Application.routes.draw do

  devise_for :users

  match "cards/audit" => "scorecards#audit"
  match "handles/:handle_id/audit" => "scorecards#audit"
  get "handles/:handle_id/reaudit" => "scorecards#reaudit"
  match "groups/:group_id/audit" => "scorecards#audit"
  match "decks/:deck_id/audit" => "scorecards#audit"
  resources :scorecards
  
  resources :users

  match "handles/:id/export" => "handles#export"
  resources :handles

  match "decks/new/:handle_id" => "decks#new"
  match "decks/:id/sort" => "decks#sort"
  resources :decks

  resources :groups
  post "groups/:id/preview" => "groups#preview"

  match "cards/:id/group/:group_id" => "cards#group"
  match "cards/:id/ungroup" => "cards#ungroup"
  resources :cards

  root :to => 'handles#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :cards
	belongs_to :deck
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.includes(:cards => :groups, :deck => [:handle]).find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def preview
    @group = Group.find params[:id]
    @questions = {}
    @group.cards.each do |c| 
      @questions[c.id] = {
        question: c.question_formatted(params[:question_format]), 
        answer: c.answer_formatted(params[:answer_format])}
    end
    render json: @questions
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to edit_group_path @group, notice: 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :ok }
    end

    # redirect_to deck_path @group.deck
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for @group, :html => { :class => 'form-horizontal' } do |f|
  - unless @group.id
    .control-group
      = f.label :name, :class => 'control-label'
      .controls
        = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :question_format, :class => 'control-label'
    .controls
      = f.text_field :question_format, :class => 'text_field'
  .control-group
    = f.label :answer_format, :class => 'control-label'
    .controls
      = f.text_field :answer_format, :class => 'text_field'
  .form-actions
    .btn-group  
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")),
        groups_path, :class => 'btn'                                

app/views/groups/edit.html.haml
- model_class = Group
%ul.breadcrumb
  %li
    = link_to @group.deck.handle.name, edit_handle_path(@group.deck.handle)
    %span.divider /
  %li
    = link_to @group.deck.title, edit_deck_path(@group.deck)
    %span.divider /
  %li.active
    %i.icon-edit
    = best_in_place @group, :name

= render :partial => 'form'

%br
%br

= render 'handles/tables'

app/views/groups/index.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.id, group_path(group) %></td>
        <td><%= group.name %></td>
        <td><%=l group.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_group_path(group), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      group_path(group),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_group_path,
            :class => 'btn btn-primary' %>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>