config/routes.rb
Quizlet::Application.routes.draw do

  devise_for :users

  match "cards/audit" => "scorecards#audit"
  match "handles/:handle_id/audit" => "scorecards#audit"
  get "handles/:handle_id/reaudit" => "scorecards#reaudit"
  match "groups/:group_id/audit" => "scorecards#audit"
  match "decks/:deck_id/audit" => "scorecards#audit"
  resources :scorecards
  
  resources :users

  match "handles/:id/export" => "handles#export"
  resources :handles

  match "decks/new/:handle_id" => "decks#new"
  match "decks/:id/sort" => "decks#sort"
  resources :decks

  resources :groups
  post "groups/:id/preview" => "groups#preview"

  match "cards/:id/group/:group_id" => "cards#group"
  match "cards/:id/ungroup" => "cards#ungroup"
  resources :cards

  root :to => 'handles#index'

end

app/models/handle.rb
class Handle < ActiveRecord::Base
	has_many :decks
  has_many :scorecards

  def grade
    bad_scorecards = Scorecard.bad :handle_id => self.id
    good_scorecards = Scorecard.good :handle_id => self.id

    good = good_scorecards.to_i.to_f
    bad = bad_scorecards.to_i.to_f
    all = good + bad
    grade = nil
    grade =  (good / all) if all > 0

    population = self.decks.map{|d| d.cards.count}.sum
    sample_size = all
    sample_size_finite = sample_size.to_f / (1 + ((sample_size-1).to_f/population))
    percentage = grade
    percentage = 0.99 if grade == 1
    percentage = 0.01 if grade == 0

    z = 1.96
    ci = nil
    ci = Math.sqrt((z**2*percentage*(1-percentage))/sample_size_finite) if sample_size > 0

    {:good => good, :bad => bad, :grade => grade, :percentage => percentage, :ci => ci, :sample_size => sample_size, :sample_size_finite => sample_size_finite, :population => population}
  end
end

app/controllers/handles_controller.rb
class HandlesController < ApplicationController
  before_filter :authenticate_user!, :except => [:export]

  # GET /handles
  # GET /handles.json 
  def index
    @handles = Handle.includes(:decks => {:cards => :scorecards}).order('created_at ASC').all

    @grades = {}
    @handles.each {|h| @grades[h.id] = h.grade}
    ap @grades

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @handles }
    end
  end

  # GET /handles/1
  # GET /handles/1.json
  def show
    @handle = Handle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @handle }
    end
  end

  # GET /handles/new
  # GET /handles/new.json
  def new
    @handle = Handle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @handle }
    end
  end

  # GET /handles/1/edit
  def edit
    @handle = Handle.includes(:decks => {:groups => {:cards => [:scorecards, :groups]}}).find(params[:id])

    # @deck_grades = {}
    # @handle.decks.each {|d| @deck_grades[d.id] = d.grade}
  end

  def export
    questions = []
    @handle = Handle.find(params[:id])
    cards = []
    @handle.decks.each {|d| d.groups.each {|g| cards += g.cards}} if @handle
    cards.each do |card|
      group = card.groups.first
      question = {}

      next if card.publish == false
      next if group.nil?
      next if group.question_format.nil? or group.answer_format.nil?
      next if group.question_format.empty? or group.answer_format.empty?

      question[:card_id] = card.id
      question[:text] = card.question_formatted
      question[:answer] = card.answer_formatted
      question[:incorrect] = []

      question[:false_answers] = []
      i = 0
      group.cards.shuffle.each do |other_card|
        next if other_card.id == card.id
        next if other_card.answer_formatted == card.answer_formatted
        next if question[:incorrect].include? other_card.answer_formatted

        i += 1
        question[:false_answers] << other_card.answer_formatted
        break if i == 3
      end


      questions << question
    end

    handle = {topic: @handle.topic, questions: questions}

    respond_to do |format|
      format.json { render json: handle }
    end
  end

  # POST /handles
  # POST /handles.json
  def create

    @deck = Deck.find_or_create_by_quizlet_id params[:handle][:decks][:quizlet_id]
    params[:handle].delete :decks
    @handle = Handle.create(params[:handle])
    @deck.handle_id = @handle.id

    require "net/https"
    require "uri"
    uri = URI.parse("https://api.quizlet.com/2.0/sets/#{@deck.quizlet_id}?client_id=ABPPhBBUAN&whitespace=1")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(request)
    @qdeck = JSON.parse response.body

    @deck.save

    @group = Group.find_or_create_by_deck_id_and_default @deck.id, true
    @group.update_attributes :name => "Default"

    @deck.title = @qdeck['title']
    @qdeck['terms'].each do |t|
      card = Card.find_or_create_by_quizlet_id t['id']
      card.front = t['term']
      card.back = t['definition']
      @deck.cards << card
      @group.cards << card
      card.save
    end

    redirect_to "/decks/#{@deck.id}/sort"
  end

  # PUT /handles/1
  # PUT /handles/1.json
  def update
    @handle = Handle.find(params[:id])

    respond_to do |format|
      if @handle.update_attributes(params[:handle])
        format.html { redirect_to @handle, notice: 'Handle was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @handle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handles/1
  # DELETE /handles/1.json
  def destroy
    @handle = Handle.find(params[:id])
    @handle.destroy

    respond_to do |format|
      format.html { redirect_to handles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/handles_helper.rb
module HandlesHelper
end

app/views/handles/_progress.html.haml
.title-container
  %h1 New Handle

- steps = ['Details', 'Group & Format', 'Audit']
.progress-container
  %ol.wizard-progress.clearfix
    - steps.each_with_index do |step, i|
      %li{:class => ("active-step" if active >= i)}
        %span.step-name= step
        %span.visuallyhidden Step
        %span.step-num= i + 1

    / %li
    /   %span.step-name Group & Format
    /   %span.visuallyhidden Step
    /   %span.step-num 2
    / %li
    /   %span.step-name Audit
    /   %span.visuallyhidden Step
    /   %span.step-num 3

    / %li
    /   %span.step-name Quux
    /   %span.visuallyhidden Step
    /   %span.step-num 4

app/views/handles/_tables.html.haml
.tabbable
  / Only required for left/right tabs
  %ul.nav.nav-tabs
    - if @handle
      %li
        %a{"data-toggle" => "tab", :href => "#tab1"} Decks

    - if @handle or @deck
      %li
        %a{"data-toggle" => "tab", :href => "#tab2"} Groups

    %li
      %a{"data-toggle" => "tab", :href => "#tab3"} Cards

    %li
      %a{"data-toggle" => "tab", :href => "#tab4"} Questions

  .tab-content
    - if @handle
      #tab1.tab-pane
        %table.table
          %tr
            %th 
            %th Title
            %th Count
            %th Quizlet id
            %th
          - @handle.decks.each_with_index do |deck, i|
            %tr
              %td= i + 1
              %td= link_to deck.title, edit_deck_path(deck)
              %td
                = deck.cards.select{|c| c.publish == true}.count
                \/
                = deck.cards.count
              %td= deck.quizlet_id
              %td
                = link_to 'Sort', "/decks/#{deck.id}/sort"
                |
                = link_to 'Destroy', deck, confirm: 'Are you sure?', method: :delete

    - if @handle or @deck
      #tab2.tab-pane
        %table.table
          %tr
            %th 
            %th Name
            %th Count
            %th Question format
            %th Answer format
            %th
          - i = 0
          - decks = (@handle) ? @handle.decks : [@deck]
          - decks.each do |deck|
            - deck.groups.each do |group|
              %tr
                %td= i += 1
                %td= link_to group.name, edit_group_path(group)
                %td
                  = group.cards.select{|c| c.publish == true}.count
                  \/
                  = group.cards.count
                %td 
                  %i.icon-edit
                  = best_in_place group, :question_format
                %td                  
                  %i.icon-edit
                  = best_in_place group, :answer_format
                %td= link_to 'Destroy', group, confirm: 'Are you sure?', method: :delete

    - cards = []
    - @handle.decks.each {|d| d.groups.each {|g| cards += g.cards}} if @handle
    - cards = @deck.cards if @deck
    - cards = @group.cards if @group

    #tab3.tab-pane
      / %h3 Listing cards
      %table.table
        %tr
          %th
          %th Front
          %th Back
          %th Publish?
          %th
        - cards.each_with_index do |card, i|
          %tr{:card_id => card.id, :group_id => (card.groups.first.id if card.groups.first)}
            %td= i + 1
            %td
              %i.icon-edit
              = best_in_place card, :front
            %td
              %i.icon-edit
              = best_in_place card, :back, :type => 'textarea'
            %td
              %i.icon-edit
              = best_in_place card, :publish, :type => :checkbox, :collection => ["No", "Yes!"]
            %td
              %a.ungroup_link Ungroup
              |
              = link_to 'Destroy', card, confirm: 'Are you sure?', method: :delete

    #tab4.tab-pane
      / %h3 Listing Questions
      %table.table
        %tr
          %th
          %th Question
          %th Answer
          %th False Answer 1
          %th False Answer 2
          %th False Answer 3

        - k = 0
        - cards.each do |card|
          - group = card.groups.first
          - next unless group
          - other_cards = group.cards.where(publish: true)
          - next if group.nil? or group.question_format.nil? or group.answer_format.nil? or !card.publish
          %tr
            %td= k += 1
            %td= card.question_formatted
            %td= card.answer_formatted
            - i = 0
            - other_cards.shuffle.each do |other_card|
              - next if other_card.id == card.id
              - if group.answer_format.include? "back"
                - next if other_card.back == card.back
              - else
                - next if other_card.front == card.front
              - i += 1
              %td= other_card.answer_formatted
              - break if i == 3

app/views/handles/edit.html.haml
- model_class = Handle
%ul.breadcrumb
  %li.active
    %i.icon-edit
    = best_in_place @handle, :name

.form-actions
  .btn-group
    = link_to "Export", "/handles/#{@handle.id}/export.json", :class => 'btn'
    = link_to "Add deck", "/decks/new/#{@handle.id}", :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")),                                 
      handle_path(@handle),                                                                          
      :method => 'delete',                                                                           
      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
      :class => 'btn btn-danger' 

%br
%br

= render 'tables'

app/views/handles/index.html.haml
- model_class = Handle
/ .page-header
/   %h1= t '.title', :default => model_class.model_name.human.pluralize

.hero-unit
  %h1 Handle management
  %br
  %p Edit, audit, destroy handles here. Or, create a new one:
  = link_to "Create a new handle", new_handle_path, :class => 'btn btn-primary btn-large'

%table.table.table-striped
  %thead
    %tr
      %th 
      %th= model_class.human_attribute_name(:name)
      %th Count
      %th Grade
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - question_count = {:published => 0, :total => 0}
    - percentages = []
    - cis = []

    / hack grades for non seeder handles
    %tr
      %td 1 
      %td QuizMeBio
      %td 
        - count = 500
        - question_count[:published] += count
        - question_count[:total] += count
        = count
      %td 
        - percentage = 0.99
        - ci = 0.03
        - percentages << percentage
        - cis << ci
        = sprintf("%.f", percentage * 100)
        = " (+/- #{sprintf "%.f", ci * 100})"
      %td
    %tr
      %td 2
      %td QuizMeChem
      %td 
        - count = 400
        - question_count[:published] += count
        - question_count[:total] += count
        = count
      %td 
        - percentage = 0.97
        - ci = 0.05
        - percentages << percentage
        - cis << ci
        = sprintf("%.f", percentage * 100)
        = " (+/- #{sprintf "%.f", ci * 100})"
      %td
    %tr
      %td 3
      %td QuizMeWeather
      %td 
        - count = 50
        - question_count[:published] += count
        - question_count[:total] += count
        = count
      %td 
        - percentage = 0.99
        - ci = 0.02
        - percentages << percentage
        - cis << ci
        = sprintf("%.f", percentage * 100)
        = " (+/- #{sprintf "%.f", ci * 100})"
      %td
    %tr
      %td 4
      %td Govt101
      %td 
        - count = 450
        - question_count[:published] += count
        - question_count[:total] += count
        = count
      %td 
        - percentage = 0.99
        - ci = 0.02
        - percentages << percentage
        - cis << ci
        = sprintf("%.f", percentage * 100)
        = " (+/- #{sprintf "%.f", ci * 100})"
      %td
    %tr
      %td 5
      %td QuizMeBeer
      %td 
        - count = 100
        - question_count[:published] += count
        - question_count[:total] += count
        = count
      %td 
        - percentage = 0.95
        - ci = 0.05
        - percentages << percentage
        - cis << ci
        = sprintf("%.f", percentage * 100)
        = " (+/- #{sprintf "%.f", ci * 100})"
      %td
    %tr
      %td 6
      %td QuizMeCycling
      %td 
        - count = 100
        - question_count[:published] += count
        - question_count[:total] += count
        = count
      %td 
        - percentage = 0.95
        - ci = 0.05
        - percentages << percentage
        - cis << ci
        = sprintf("%.f", percentage * 100)
        = " (+/- #{sprintf "%.f", ci * 100})"
      %td

    - i = 6
    - @handles.each do |handle|
      - published_count = handle.decks.map{|d| d.cards}.flatten.select{|c| c.publish == true}.count
      - total = handle.decks.map{|d| d.cards}.flatten.count
      - question_count[:published] += published_count
      - question_count[:total] += total
      
      %tr
        %td
          - if handle.published
            - i += 1
            = i
        %td= link_to handle.name, edit_handle_path(handle)
        %td
          = published_count
          \/
          = total
        %td
          - if handle.published
            - percentages << @grades[handle.id][:percentage] if @grades[handle.id][:percentage]
            - cis << @grades[handle.id][:ci] if @grades[handle.id][:ci]
            = sprintf("%.f", @grades[handle.id][:percentage] * 100) if @grades[handle.id][:percentage]
            = " (+/- #{sprintf "%.f", @grades[handle.id][:ci] * 100})" if @grades[handle.id][:ci]
        %td
          = link_to "Export", "/handles/#{handle.id}/export.json"
          &nbsp;|&nbsp;
          = link_to t('.destroy', :default => t("helpers.links.destroy")),                                 
            handle_path(handle),                                                                           
            :method => :delete,                                                                            
            :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))
          &nbsp;|&nbsp;
          = link_to "Audit", "/handles/#{handle.id}/audit"
          &nbsp;|&nbsp;
          %a{:style => 'cursor:pointer;'}= best_in_place handle, :published, :type => :checkbox, :collection => ["Publish", "Unpublish"]
    %tr.well
      %td
      %td
      %td
        %strong= "#{question_count[:published]}/#{question_count[:total]}"
      %td
        %strong
          - if cis.count > 0
            = "#{sprintf("%.f", percentages.sum/percentages.count * 100)}% (+/- #{sprintf("%.f", cis.sum/cis.count * 100)})"
      %td

app/views/handles/new.html.haml
= render "progress", active: 0

.handles-new
  .form-well.well.span5.offset3
    = form_for @handle, :html => { :class => 'form-horizontal' } do |f|
      .control-group
        = f.label :name, :class => 'control-label'
        .controls
          = f.text_field :name, :class => 'text_field'
      .control-group
        = f.label :topic, :class => 'control-label'
        .controls
          = f.text_field :topic, :class => 'text_field'
          %p
            %i
              %small This will autopopulate the description

      = f.fields_for :decks do |ff|
        .control-group
          = ff.label "Quizlet Id", :class => 'control-label'
          .controls
            = ff.text_field :quizlet_id, :class => 'quizlet_id'

      .form-actions
        = f.submit nil, :class => 'btn btn-primary btn-large'
        = link_to t('.cancel', :default => t("helpers.links.cancel")),
          handles_path, :class => 'btn btn-large'

app/views/handles/test.html.haml
/%script{:src => "http://www.magic-dev.com/demo/jquery-1.6.2.min.js", :type => "text/javascript"}
/%script{:src => "http://www.magic-dev.com/demo/jquery-ui-1.8.14.custom.min.js", :type => "text/javascript"}
:css
  .listdragable{ background:#FFFFCC; list-style-type: none; width:140px; margin: 0; padding: 5px; float: left; margin-right: 10px; }
  .listdragable li { margin: 5px; padding: 5px; font:10 tahoma; width: 120px; }
  .listdragable li i { cursor:move; }
  .list li {background:#E1E1FF;}

%div
  .list#list1
    .drag_cont
    %ul.listdragable.selectable
      %li
        %i.icon-move
        Item 1
      %li
        %i.icon-move
        Item 2
      %li
        %i.icon-move
        Item 3
  .list#list2
    .drag_cont
    %ul.listdragable.selectable
      %li
        %i.icon-move
        Item 4
      %li
        %i.icon-move
        Item 5
      %li
        %i.icon-move
        Item 6
  .list#list3
    .drag_cont
    %ul.listdragable.selectable
      %li
        %i.icon-move
        Item 7
      %li
        %i.icon-move
        Item 8
      %li
        %i.icon-move
        Item 9